/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package server_javacard;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import service.Service;

/**
 *
 * @author DEH EUGENE
 */
public class Server_javacard extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Client client;
    private Object data[][] = null;
    private boolean edit=false;
    /**
     * Creates new form Server_javacard
     */
    public Server_javacard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNouveau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldNvNom = new javax.swing.JTextField();
        textFieldNvPrenom = new javax.swing.JTextField();
        comboSexe = new javax.swing.JComboBox();
        textFieldNvCni = new javax.swing.JTextField();
        textFieldNvCompte = new javax.swing.JTextField();
        textFieldNvSolde = new javax.swing.JTextField();
        btnValiderNouveau = new javax.swing.JButton();
        btnAnnulerNouveau = new javax.swing.JButton();
        panelListe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListe = new javax.swing.JTable();
        btnEditer = new javax.swing.JButton();
        btnActDes = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnListe = new javax.swing.JButton();
        btnCrediter = new javax.swing.JButton();
        btnNouveau = new javax.swing.JButton();
        panelCrediter = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textFieldCreditCompte = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldCreditSolde = new javax.swing.JTextField();
        btnValiderCrediter = new javax.swing.JButton();
        btnAnnulerCrediter = new javax.swing.JButton();
        labelRendu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("Gestion des clients");
        panelNouveau.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NOM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PRENOM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SEXE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CNI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("COMPTE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("SOLDE");

        comboSexe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masculin", "féminin" }));

        textFieldNvCompte.setEditable(false);
        textFieldCreditCompte.setEditable(false);
        textFieldCreditCompte.setFocusable(false);
        textFieldNvCompte.setFocusable(false);

        textFieldNvSolde.setText("");

        btnValiderNouveau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnValiderNouveau.setText("Valider");
        btnValiderNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderNouveauActionPerformed(evt);
            }
        });

        btnAnnulerNouveau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAnnulerNouveau.setText("Annuler");
        btnAnnulerNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerNouveauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNouveauLayout = new javax.swing.GroupLayout(panelNouveau);
        panelNouveau.setLayout(panelNouveauLayout);
        panelNouveauLayout.setHorizontalGroup(
            panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNouveauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValiderNouveau)
                    .addComponent(comboSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldNvNom)
                        .addComponent(textFieldNvPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelNouveauLayout.createSequentialGroup()
                        .addComponent(btnAnnulerNouveau)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelNouveauLayout.createSequentialGroup()
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNvCompte)
                            .addComponent(textFieldNvCni)
                            .addComponent(textFieldNvSolde, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelNouveauLayout.setVerticalGroup(
            panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNouveauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNouveauLayout.createSequentialGroup()
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textFieldNvNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textFieldNvPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelNouveauLayout.createSequentialGroup()
                        .addComponent(textFieldNvCni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNvCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textFieldNvSolde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panelNouveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulerNouveau)
                    .addComponent(btnValiderNouveau))
                .addContainerGap())
        );

        panelListe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnListeActionPerformed();
        tableListe.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListe);
        tableListe.getColumnModel().getColumn(0).setResizable(false);
        tableListe.getColumnModel().getColumn(1).setResizable(false);
        tableListe.getColumnModel().getColumn(2).setResizable(false);
        tableListe.getColumnModel().getColumn(3).setResizable(false);
        tableListe.getColumnModel().getColumn(4).setResizable(false);
        tableListe.getColumnModel().getColumn(5).setResizable(false);
        tableListe.getColumnModel().getColumn(6).setResizable(false);
        tableListe.getColumnModel().getColumn(7).setResizable(false);

        btnEditer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditer.setText("Editer client");
        btnEditer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditerActionPerformed(evt);
            }
        });

        btnActDes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActDes.setText("Activer");
        btnActDes.setVisible(false);
        btnActDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActDesActionPerformed(evt);
            }
        });

        btnSupprimer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.setVisible(false);
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListeLayout = new javax.swing.GroupLayout(panelListe);
        panelListe.setLayout(panelListeLayout);
        panelListeLayout.setHorizontalGroup(
            panelListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListeLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnEditer)
                .addGap(73, 73, 73)
                .addComponent(btnActDes)
                .addGap(52, 52, 52)
                .addComponent(btnSupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        panelListeLayout.setVerticalGroup(
            panelListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditer)
                    .addComponent(btnActDes)
                    .addComponent(btnSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnListe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListe.setText("Raffraichir Liste");
        btnListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeActionPerformed();
            }
        });
        
        btnCrediter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrediter.setText("Créditer compte");
        btnCrediter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrediterActionPerformed();
            }
        });

        btnNouveau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNouveau)
                .addGap(45, 45, 45)
                .addComponent(btnListe)
                .addGap(45, 45, 45)
                .addComponent(btnCrediter)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                	.addComponent(btnCrediter)
                    .addComponent(btnListe)
                    .addComponent(btnNouveau))
                .addContainerGap())
        );

        panelCrediter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("COMPTE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("SOLDE");

        btnValiderCrediter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnValiderCrediter.setText("Valider");
        btnValiderCrediter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderCrediterActionPerformed(evt);
            }
        });

        btnAnnulerCrediter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAnnulerCrediter.setText("Annuler");
        btnAnnulerCrediter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerCrediterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrediterLayout = new javax.swing.GroupLayout(panelCrediter);
        panelCrediter.setLayout(panelCrediterLayout);
        panelCrediterLayout.setHorizontalGroup(
            panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrediterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrediterLayout.createSequentialGroup()
                        .addGroup(panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrediterLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldCreditSolde, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrediterLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldCreditCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrediterLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnValiderCrediter, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnnulerCrediter)
                        .addGap(31, 31, 31))))
        );
        panelCrediterLayout.setVerticalGroup(
            panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrediterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCreditCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCreditSolde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCrediterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulerCrediter)
                    .addComponent(btnValiderCrediter))
                .addContainerGap())
        );

        labelRendu.setForeground(new java.awt.Color(250, 51, 0));
        labelRendu.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CREDITER COMPTE");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NOUVEAU CLIENT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("LISTE DES CLIENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(panelNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelRendu, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(418, 418, 418)
                                    .addComponent(jLabel10)
                                    .addGap(157, 157, 157)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelCrediter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRendu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCrediter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pack();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation(dim.width/2 - this.getWidth()/2, dim.height/2 - this.getHeight()/2);
    }// </editor-fold>                        

    private void btnValiderCrediterActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        client = new Client();
        String cp = textFieldCreditCompte.getText().trim();
        String sold = textFieldCreditSolde.getText().trim();
        if(!cp.isEmpty()&& !sold.isEmpty()&& validerMontant(sold)&& validerMontant(cp)){
        client.read(cp);
        client.setSolde(client.getSolde() + Integer.parseInt(sold));
        client.saveSolde();
        labelRendu.setText(Service.messageRendu);
        btnListeActionPerformed();
        textFieldCreditCompte.setText(null);
        textFieldCreditSolde.setText(null);
        }else{labelRendu.setText("Vérifier que le montant saisi est correct");}
        
    }                                                  

    private void btnAnnulerCrediterActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        textFieldCreditCompte.setText(null);
        textFieldCreditSolde.setText(null);
    }                                                  

    private void btnListeActionPerformed() {                                         
        ArrayList<Client> array = Service.listeClient();
        int i, size = array.size();
        data = new Object[size][8];
        btnEditer.setVisible(false);
        btnSupprimer.setVisible(false);
        btnActDes.setVisible(false);
        labelRendu.setText("");
        Client cli = new Client();
        for (i = 0; i < size; i++) {
            cli = array.get(i);
            data[i][0] = cli.getNumCompt();
            data[i][1] = cli.getNom().toUpperCase();
            data[i][2] = cli.getPrenom().toUpperCase();
            data[i][3] = cli.getSexe().toUpperCase();
            data[i][4] = cli.getCni();
            data[i][5] = cli.getSolde();
            data[i][6] = (cli.getEtat() > 0 ? true : false);
            data[i][7] = (cli.getEtat() > 0 ? "activer" : "désactiver");
        }
        tableListe.setCellEditor(null);
        tableListe.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
            "COMPTE", "NOM", "PRENOM", "SEXE", "CNI", "SOLDE", "ETAT", "ACT/DES"
        }) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return data[0][columnIndex].getClass();

            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        this.tableListe.setRowHeight(30);


    }                                        

    private void btnValiderNouveauActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        if(validerMontant(textFieldNvSolde.getText().trim())&&validerNom(textFieldNvNom.getText().trim())&& 
                validerNom(textFieldNvPrenom.getText().trim())&&validerCni(textFieldNvCni.getText().trim())){
        if (edit == false) {
        	client = new Client(textFieldNvCompte.getText().trim(),
                    textFieldNvNom.getText().trim(), textFieldNvPrenom.getText().trim(),
                    (String) comboSexe.getSelectedItem(), textFieldNvCni.getText().trim(),
                    "0000", Integer.parseInt(textFieldNvSolde.getText().trim()), 1,0);
            client.save();
            btnListeActionPerformed();
        } else {
        	client = new Client(textFieldNvCompte.getText().trim(),
                    textFieldNvNom.getText().trim(), textFieldNvPrenom.getText().trim(),
                    (String) comboSexe.getSelectedItem(), textFieldNvCni.getText().trim(),
                    "0000", Integer.parseInt(textFieldNvSolde.getText().trim()), 1,client.getEtatSupp());
            client.update();
            btnListeActionPerformed();
            edit = false;
        }
        labelRendu.setText(Service.messageRendu);
        }else{labelRendu.setText("Un de champ est incorrect : veuillez vérifier SVP"); }
        textFieldNvCompte.setText("");
        textFieldNvNom.setText("");
        textFieldNvPrenom.setText("");
        textFieldNvCni.setText("");
        textFieldNvSolde.setText("");
    }                                                 

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) { 
    	labelRendu.setText("");
    	edit = false;
    	labelRendu.setText("");
    	textFieldNvNom.setText("");
    	textFieldNvPrenom.setText("");
    	textFieldNvCni.setText("");
    	textFieldNvSolde.setText("");
        textFieldNvCompte.setText(Integer.toString(Service.genererNumCompte() + 1));
        
    }                                          

    private void btnEditerActionPerformed(java.awt.event.ActionEvent evt) {                                          
        edit = true;
        labelRendu.setText("");
        int select = tableListe.getSelectedRow();
        if (select >= 0) {
            textFieldNvCompte.setText((String) data[select][0]);
            textFieldNvCompte.setEditable(false);
            textFieldNvNom.setText((String) data[select][1]);
            textFieldNvPrenom.setText((String) data[select][2]);
            if("FÉMININ".equals(data[select][3])){
            	comboSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"féminin" , "masculin" }));
            }else{
            	comboSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masculin", "féminin" }));
            }
            textFieldNvCni.setText("" + data[select][4]);
            textFieldNvSolde.setText("" + data[select][5]);
        }
    }  
    
    private void btnCrediterActionPerformed() {                                          
        edit = true;
        labelRendu.setText("");
        int select = tableListe.getSelectedRow();
        if (select >= 0) {
            textFieldCreditCompte.setText((String) data[select][0]);
        }else{labelRendu.setText("Sélectionner d'abord le client SVP");}
    }

    private void tableListeMouseClicked(java.awt.event.MouseEvent evt) {                                        
        if (tableListe.getSelectedRow() >= 0) {            
            btnActDes.setVisible(true);
            btnSupprimer.setVisible(true);
            int p=tableListe.getSelectedRow();
            if((((String)(data[p][7])).trim()=="désactiver")){btnActDes.setText("Activer");}else{btnActDes.setText("Désactiver");}
            btnEditer.setVisible(true);
        }
    }                                       

    private void btnActDesActionPerformed(java.awt.event.ActionEvent evt) { 
    	int p1,i=0;
    	int[] tab = tableListe.getSelectedRows();
        if (tab.length > 0) {
        	for(i=0;i<tab.length;i++){
            p1=tab[i];
            boolean p= (Boolean) data[p1][6];
            btnEditer.setVisible(true);
            Service.saveEtat(((String)(data[p1][0])).trim(),p);
            data[p1][6]=!p;
            data[p1][7] = (p==true ? "désactiver" : "activer");
        }
        	labelRendu.setText("Activation/désactivation effectuée avec succès");
            btnListeActionPerformed();
            }
    }                                         

    private void btnAnnulerNouveauActionPerformed(java.awt.event.ActionEvent evt) { 
    	labelRendu.setText("");
        textFieldNvCompte.setText(null);
        textFieldNvNom.setText(null);
        textFieldNvPrenom.setText(null);
        textFieldNvCni.setText(null);
        textFieldNvSolde.setText(null);
    }                                                 

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	int p1,i=0;
    	String p=null;
    	int[] tab = tableListe.getSelectedRows();
        if (tab.length > 0) {
        	for(i=0;i<tab.length;i++){
            p1=tab[i];
            p = (String)data[p1][0];
            Service.suppClient(p.trim());
        }
            labelRendu.setText("Suppression effectuée avec succès");
            btnListeActionPerformed();
        }
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_javacard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_javacard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_javacard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_javacard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_javacard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnActDes;
    private javax.swing.JButton btnAnnulerCrediter;
    private javax.swing.JButton btnAnnulerNouveau;
    private javax.swing.JButton btnEditer;
    private javax.swing.JButton btnCrediter;
    private javax.swing.JButton btnListe;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnValiderCrediter;
    private javax.swing.JButton btnValiderNouveau;
    private javax.swing.JComboBox comboSexe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRendu;
    private javax.swing.JPanel panelCrediter;
    private javax.swing.JPanel panelListe;
    private javax.swing.JPanel panelNouveau;
    private javax.swing.JTable tableListe;
    private javax.swing.JTextField textFieldCreditCompte;
    private javax.swing.JTextField textFieldCreditSolde;
    private javax.swing.JTextField textFieldNvCni;
    private javax.swing.JTextField textFieldNvCompte;
    private javax.swing.JTextField textFieldNvNom;
    private javax.swing.JTextField textFieldNvPrenom;
    private javax.swing.JTextField textFieldNvSolde;
    // End of variables declaration                   

    private boolean validerMontant(String text) {
		return text.matches("^[1-9][0-9]*$")&& (Integer.parseInt(text)>0);
	}
    private boolean validerCni(String text) {
		return text.matches("^[1-9][0-9]*$")&& (Integer.parseInt(text)>0) && text.length()==9;
	}
    private boolean validerNom(String text) {
		return (text.matches("^[a-z A-Z é è É È ë ï Ë Ï]+$")&& text.length()>=3);
	}
}
